## Data Quality Report

In [2]:
import pandas as pd

### Dataset 1: Census Data

In [3]:
census_data = pd.read_csv("census_data.csv")
census_data.head()

,name,cbsa_code,median_income,total_population,population_25_plus,hs_diploma,ged,associates,bachelors,masters,professional,doctorate
0,"Aberdeen, SD Micro Area",10100,71488,41925,27808,7188,1029,3383,6310,2073,382,473
1,"Aberdeen, WA Micro Area",10140,64414,77053,56642,14783,4370,7321,6906,2603,568,204
2,"Abilene, TX Metro Area",10180,67328,180408,114622,27645,8555,10509,19850,8220,1434,943
3,"Ada, OK Micro Area",10220,63017,38235,25247,7147,1142,1905,4694,2249,247,456
4,"Adrian, MI Micro Area",10300,70518,98415,69411,21193,3479,7185,10274,4455,538,468

#### Completeness

In [4]:
census_data.dtypes

name                    str
cbsa_code             int64
median_income         int64
total_population      int64
population_25_plus    int64
hs_diploma            int64
ged                   int64
associates            int64
bachelors             int64
masters               int64
professional          int64
doctorate             int64
dtype: object

The census data does not appear to have missing values. Since we converted all of the Census's default missing values to None/NaN in `fetch_census_data.py`, if there were missing values in `census_data.csv`, the dtypes for the column would indicate `object` or `float64`, not `str` or `int64`.

While this data does have complete data for all of the Micro/Metro areas that have a CBSA, it is not complete in the sense that there are significant portions of the United States that are not a part of a CBSA. Rural and sparsely populated areas will be excluded from this analysis simply because they do not a high enough population to be a part of a CBSA.

#### Accuracy

In [14]:
census_data["name"].values.unique

<bound method NDArrayBackedExtensionArray.unique of <StringArray>
[         'Aberdeen, SD Micro Area',          'Aberdeen, WA Micro Area',
           'Abilene, TX Metro Area',               'Ada, OK Micro Area',
            'Adrian, MI Micro Area',         'Aguadilla, PR Metro Area',
             'Akron, OH Metro Area',        'Alamogordo, NM Micro Area',
           'Alamosa, CO Micro Area',            'Albany, GA Metro Area',
 ...
         'Worcester, MA Metro Area',       'Worthington, MN Micro Area',
            'Yakima, WA Metro Area',           'Yankton, SD Micro Area',
      'York-Hanover, PA Metro Area', 'Youngstown-Warren, OH Metro Area',
         'Yuba City, CA Metro Area',              'Yuma, AZ Metro Area',
        'Zanesville, OH Micro Area',            'Zapata, TX Micro Area']
Length: 935, dtype: str>

This dataset does not appear to suffer from syntactic accuracy issues. The dataset has consistent capitalization and formatting in the `names` column.

Semantic accuracy is unfortunately difficult to check. For example, it would be challenging to check the total population of a specific CBSA without querying the census itself. The same can be said with most of the other columns in this dataset. There is not another authoritative source we can check to verify that the data in this dataset is correct. The population also is expected to change over time and may be suspect to drastic fluctuations, so checking this data against the older 2023 dataset for accuracy may not be a great way to check for semantic accuracy.

#### Consistency

One rule that this data must satisfy is that the column `population_25_plus` must be greater than or equal to the sum of `hs_diploma`, `ged`, `associates`, `bachelors`, `masters`, `professional`, and `doctorate`. We will check that in the code cell below.

In [17]:
test = census_data[census_data["population_25_plus"] >= census_data["hs_diploma"] 
                   + census_data["ged"] + census_data["associates"]
                   + census_data["bachelors"] + census_data["masters"] 
                   + census_data["professional"] + census_data["doctorate"]]
assert(test.shape == census_data.shape)
print("Assertion Passed")

Assertion Passed

Another rule that this data must satisfy is that the column `total_population` must be greater than or equal to `population_25_plus`. We check this in the code cell below.

In [18]:
test = census_data[census_data["total_population"] >= census_data["population_25_plus"]]
assert(test.shape == census_data.shape)
print("Assertion Passed")

Assertion Passed

Both rules are satisfied in this dataset.

#### Timeliness

This specific dataset will not change over time. We are using the 2024 American Community Survey data from the Census, which once it is published will not change. The values that we see now should be the same even into the future.

This dataset should be appropriate to use. This data is from the most recent published American Community Survey as of April 2026. It should remain appropriate to use for about the next year or until the next American Community Survey is published.

### Dataset 2: Public School Data

In [20]:
public_school_data = pd.read_csv("public_schools.csv")
public_school_data.head()

,NCESSCH,LEAID,NAME,OPSTFIPS,STREET,CITY,STATE,ZIP,STFIP,CNTY,...,LON,CBSA,NMCBSA,CBSATYPE,CSA,NMCSA,CD,SLDL,SLDU,SCHOOLYEAR
0,10000500870,100005,Albertville Middle School,1,600 E Alabama Ave,Albertville,AL,35950,1,1095,...,-86.206200,10700,"Albertville, AL",2,290,"Huntsville-Decatur-Albertville, AL-TN",104,01026,01009,2024-2025
1,10000500871,100005,Albertville High School,1,402 E McCord Ave,Albertville,AL,35950,1,1095,...,-86.204911,10700,"Albertville, AL",2,290,"Huntsville-Decatur-Albertville, AL-TN",104,01026,01009,2024-2025
2,10000500879,100005,Albertville Intermediate School,1,901 W McKinney Ave,Albertville,AL,35950,1,1095,...,-86.220154,10700,"Albertville, AL",2,290,"Huntsville-Decatur-Albertville, AL-TN",104,01026,01009,2024-2025
3,10000500889,100005,Albertville Elementary School,1,145 West End Drive,Albertville,AL,35950,1,1095,...,-86.221806,10700,"Albertville, AL",2,290,"Huntsville-Decatur-Albertville, AL-TN",104,01026,01009,2024-2025
4,10000501616,100005,Albertville Kindergarten and PreK,1,257 Country Club Rd,Albertville,AL,35951,1,1095,...,-86.193056,10700,"Albertville, AL",2,290,"Huntsville-Decatur-Albertville, AL-TN",104,01026,01009,2024-2025

#### Completeness

In [21]:
public_school_data.dtypes

NCESSCH         int64
LEAID           int64
NAME              str
OPSTFIPS        int64
STREET            str
CITY              str
STATE             str
ZIP             int64
STFIP           int64
CNTY            int64
NMCNTY            str
LOCALE          int64
LAT           float64
LON           float64
CBSA              str
NMCBSA            str
CBSATYPE        int64
CSA               str
NMCSA             str
CD              int64
SLDL              str
SLDU              str
SCHOOLYEAR        str
dtype: object

In [29]:
public_school_data["LAT"].value_counts()

LAT
31.391031    30
30.618340    29
32.730020    18
29.684409    14
33.248888    14
             ..
18.330464     1
18.341950     1
18.338742     1
18.354782     1
18.318230     1
Name: count, Length: 89103, dtype: int64

In [25]:
public_school_data["LON"].value_counts()

LON
-100.402958    30
-97.659021     29
-97.390519     18
-95.417276     14
-96.634636     14
               ..
-64.793916      1
-64.917602      1
-64.952483      1
-64.899024      1
-64.890311      1
Name: count, Length: 90923, dtype: int64

This dataset does not appear to contain any explicit missing values. If there were explicit missing values, we should have seen that represented in our `dtypes` showing either `object` or `float64`, and we should have seen missing values in the `LAT` or `LON` columns.

In [37]:
public_school_data["CITY"].value_counts()

CITY
HOUSTON        803
Chicago        655
SAN ANTONIO    585
BROOKLYN       585
Los Angeles    573
              ...
TALOFOFO         1
PITI             1
Dededo           1
Agat             1
CULEBRA          1
Name: count, Length: 14469, dtype: int64

In [73]:
public_school_data[(public_school_data["STREET"] == "M") | (public_school_data["STREET"] == "M")]

Empty DataFrame
Columns: [NCESSCH, LEAID, NAME, OPSTFIPS, STREET, CITY, STATE, ZIP, STFIP, CNTY, NMCNTY, LOCALE, LAT, LON, CBSA, NMCBSA, CBSATYPE, CSA, NMCSA, CD, SLDL, SLDU, SCHOOLYEAR]
Index: []

[0 rows x 23 columns]

In [27]:
public_school_data["CBSA"].value_counts()

CBSA
N        11236
35620     4737
31080     2873
16980     2659
19100     2376
         ...
49820        6
22340        5
45880        5
45580        4
34880        4
Name: count, Length: 936, dtype: int64

In [31]:
public_school_data["NMCBSA"].value_counts()

NMCBSA
N                                     11236
New York-Newark-Jersey City, NY-NJ     4737
Los Angeles-Long Beach-Anaheim, CA     2873
Chicago-Naperville-Elgin, IL-IN        2659
Dallas-Fort Worth-Arlington, TX        2376
                                      ...
Zapata, TX                                6
Fitzgerald, GA                            5
Town of Pecos, TX                         5
Thomaston, GA                             4
Nantucket, MA                             4
Name: count, Length: 936, dtype: int64

As we can see from the analysis above, we are missing values in some columns, specifically in the `CBSA` and the `NMCBSA` columns (which are the columns that we care the most about because we have to join on these columns). The notation "N" likely indicates the missing data.

The "N" likely means that the public school in question is probably not in a CBSA. We verify this using an example below:

In [40]:
test = public_school_data[public_school_data["CBSA"] == "N"]
test.head()

,NCESSCH,LEAID,NAME,OPSTFIPS,STREET,CITY,STATE,ZIP,STFIP,CNTY,...,LON,CBSA,NMCBSA,CBSATYPE,CSA,NMCSA,CD,SLDL,SLDU,SCHOOLYEAR
79,10006000007,100060,Andalusia High School,1,701 Third St,Andalusia,AL,36420,1,1039,...,-86.470998,N,N,0,N,N,101,01092,01031,2024-2025
80,10006000008,100060,Andalusia Junior High,1,408 4th Avenue,Andalusia,AL,36420,1,1039,...,-86.470935,N,N,0,N,N,101,01092,01031,2024-2025
81,10006001467,100060,Andalusia Elementary School,1,1501 West Bypass,Andalusia,AL,36474,1,1039,...,-86.502500,N,N,0,N,N,101,01092,01031,2024-2025
138,10019902452,100199,University Charter School Elementary,1,108 North Street,Livingston,AL,35470,1,1119,...,-88.189067,N,N,0,N,N,107,01071,01024,2024-2025
139,10019902557,100199,University Charter School Secondary,1,134 University Drive,Livingston,AL,35470,1,1119,...,-88.186266,N,N,0,N,N,107,01071,01024,2024-2025

Andalusia, AL, is located in Covington County. Covington County is not in a CBSA (according to [this map](https://www2.census.gov/geo/maps/metroarea/stcbsa_pg/Feb2013/cbsa2013_AL.pdf) of CBSAs in Alabama).

Similarly, Livingston, AL, is located in Sumter County. Sumter County is not in a CBSA according to the same map.

As a result, the missing values in the `CBSA` columns are highly likely due to the fact that these public schools are located in a region that is not encompassed by a CBSA. As a result, this missing data is likely intentional and not retrievable.

Ideally we should be more thorough and check every single entry, but doing so would require much more data (for example, every single city/county in every state) and is likely not feasible given the timeline of the project. This will be considered for future work.

#### Accuracy

In [42]:
public_school_data["CITY"].value_counts()

CITY
HOUSTON        803
Chicago        655
SAN ANTONIO    585
BROOKLYN       585
Los Angeles    573
              ...
TALOFOFO         1
PITI             1
Dededo           1
Agat             1
CULEBRA          1
Name: count, Length: 14469, dtype: int64

In [41]:
public_school_data["STREET"].value_counts()

STREET
2405 FAIRVIEW SCHOOL RD      27
200 WILCO WAY                23
6300 NW 27TH AVE             17
Main St                      13
50 Moreland Rd.              12
                             ..
14 18 ESTATE ENIGHED          1
41 ESTATE THOMAS              1
7B ESTATE CONTANT             1
15B and 16 ESTATE MANDAHL     1
9 1 and 12A BOVONI            1
Name: count, Length: 92822, dtype: int64

This dataset suffers from both syntactic and semantic errors.

We can see that there is inconsistent capitalization and formatting in both the `CITY` and `STREET` columns. Sometimes, city names are capitalized, but other times they are not. "Road" is sometimes written "RD" or "Rd." depending on the entry. These contribute to syntactic errors.

The `STREET` column also suffers from semantic accuracy. For example, 13 public schools have their street address as simply "Main St" with no building number. This is a semantic error, as a school building should have a building number. We can see also that some schools also have multiple building numbers (for example, "9 1 and 12A").

While we can fix the syntactic errors, we do not see a way to fix the semantic errors in a timely manner, if at all. The address data of each school cannot be easily found without scraping websites of schools or asking the schools themselves.

#### Consistency

A rule that must be satisfied is that each CBSA code should match to exactly 1 NMCBSA. We check that below.

In [67]:
cbsa_counts = public_school_data["CBSA"].value_counts()
nmcbsa_counts = public_school_data["NMCBSA"].value_counts()

for ((k1, _), (k2, _)) in zip(cbsa_counts.items(), nmcbsa_counts.items()):
    if k1 != "N":
        count_cbsa = cbsa_counts[k1]
        count_nmcbsa = nmcbsa_counts[k2]
        assert(count_cbsa == count_nmcbsa)
    else:
        assert(cbsa_counts[k1] == nmcbsa_counts[k2])

print("Assertions Passed")

Assertions Passed

The counts for each CBSA and NMCBSA match. While we can also check the other columns (namely `CSA` and `NMCSA`), we will remove those columns when we process the data in the data cleaning stage.

#### Timeliness

This particular dataset will not change over time. We are using the 2024-25 school location data from the Education Department, which should not change after the data is published. The data we see now should be the same into the future.

This data is from the 2024-25 school year, the most recent data available as of April 2026. This data should be suitable to use until the 2025-26 school year data is published by the Education Department.

### Dataset 3: Postsecondary School Data

In [72]:
postsecondary = pd.read_csv("postsecondary_schools.csv")
postsecondary.head()

,UNITID,NAME,STREET,CITY,STATE,ZIP,STFIP,CNTY,NMCNTY,LOCALE,...,LON,CBSA,NMCBSA,CBSATYPE,CSA,NMCSA,CD,SLDL,SLDU,SCHOOLYEAR
0,100654,Alabama A & M University,4900 Meridian Street,Normal,AL,35762,01,01089,Madison County,12,...,-86.568502,26620,"Huntsville, AL",1,290,"Huntsville-Decatur-Albertville, AL-TN",0105,01019,01008,2024-2025
1,100663,University of Alabama at Birmingham,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,01,01073,Jefferson County,12,...,-86.799345,13820,"Birmingham, AL",1,142,"Birmingham-Cullman-Talladega, AL",0107,01055,01018,2024-2025
2,100690,Amridge University,1200 Taylor Rd,Montgomery,AL,36117-3553,01,01101,Montgomery County,12,...,-86.174010,33860,"Montgomery, AL",1,388,"Montgomery-Selma, AL",0102,01078,01025,2024-2025
3,100706,University of Alabama in Huntsville,301 Sparkman Dr,Huntsville,AL,35899,01,01089,Madison County,12,...,-86.640449,26620,"Huntsville, AL",1,290,"Huntsville-Decatur-Albertville, AL-TN",0105,01053,01002,2024-2025
4,100724,Alabama State University,915 S Jackson Street,Montgomery,AL,36104-0271,01,01101,Montgomery County,12,...,-86.295677,33860,"Montgomery, AL",1,388,"Montgomery-Selma, AL",0102,01077,01026,2024-2025

#### Completeness

In [74]:
postsecondary.dtypes

UNITID          int64
NAME              str
STREET            str
CITY              str
STATE             str
ZIP               str
STFIP             str
CNTY              str
NMCNTY            str
LOCALE            str
LAT           float64
LON           float64
CBSA              str
NMCBSA            str
CBSATYPE        int64
CSA               str
NMCSA             str
CD                str
SLDL              str
SLDU              str
SCHOOLYEAR        str
dtype: object

In [76]:
postsecondary["LAT"].value_counts()

LAT
39.772948    4
34.039355    3
34.044209    3
38.904881    3
41.797895    3
            ..
42.882294    1
29.944388    1
35.596425    1
27.989284    1
33.791110    1
Name: count, Length: 6474, dtype: int64

In [77]:
postsecondary["LON"].value_counts()

LON
-86.172217     4
-118.259680    3
-118.259930    3
-77.034133     3
-87.585989     3
              ..
-85.604279     1
-90.073308     1
-106.012848    1
-81.663051     1
-84.622929     1
Name: count, Length: 6474, dtype: int64

This dataset does not appear to contain any explicit missing values. If there were explicit missing values, we should have seen that represented in our `dtypes` showing either `object` or `float64`, and we should have seen missing values in the `LAT` or `LON` columns.

In [80]:
postsecondary["CITY"].value_counts()

CITY
New York            76
Chicago             72
Houston             67
Los Angeles         56
Brooklyn            53
                    ..
SOUTHFILED USA       1
East Point           1
Suprise              1
Maryland Heights     1
Lithia Springs       1
Name: count, Length: 2376, dtype: int64

In [82]:
postsecondary[(postsecondary["STREET"] == "M") | (postsecondary["STREET"] == "M")]

,UNITID,NAME,STREET,CITY,STATE,ZIP,STFIP,CNTY,NMCNTY,LOCALE,...,LON,CBSA,NMCBSA,CBSATYPE,CSA,NMCSA,CD,SLDL,SLDU,SCHOOLYEAR
10,100858,Auburn University,M,Auburn,AL,36849,01,01081,Lee County,13,...,-85.488258,12220,"Auburn-Opelika, AL",1,194,"Columbus-Auburn-Opelika, GA-AL",0103,01079,01027,2024-2025
1499,163286,University of Maryland-College Park,M,College Park,MD,20742,24,24033,Prince George's County,21,...,-76.944721,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV",1,548,"Washington-Baltimore-Arlington, DC-MD-VA-WV-PA",2404,24021,24021,2024-2025
1626,168148,Tufts University,M,Medford,MA,02155-5555,25,25017,Middlesex County,21,...,-71.118293,14460,"Boston-Cambridge-Newton, MA-NH",1,148,"Boston-Worcester-Providence, MA-RI-NH",2505,25092,25D27,2024-2025
1708,171100,Michigan State University,M,East Lansing,MI,48824-1046,26,26065,Ingham County,13,...,-84.476111,29620,"Lansing-East Lansing, MI",1,330,"Lansing-East Lansing-Owosso, MI",2607,26073,26028,2024-2025
2367,193654,The New School,M,New York,NY,10011,36,36061,New York County,11,...,-73.997114,35620,"New York-Newark-Jersey City, NY-NJ",1,408,"New York-Newark, NY-NJ-CT-PA",3610,36066,36027,2024-2025
2707,203128,Hiram College,M,Hiram,OH,44234-0067,39,39133,Portage County,42,...,-81.143981,10420,"Akron, OH",1,184,"Cleveland-Akron-Canton, OH",3914,39072,39027,2024-2025
3360,222178,Abilene Christian University,M,Abilene,TX,79699,48,48441,Taylor County,12,...,-99.709797,10180,"Abilene, TX",1,101,"Abilene-Sweetwater, TX",4819,48071,48028,2024-2025
3672,234085,Virginia Military Institute,M,Lexington,VA,24450-0304,51,51678,Lexington city,32,...,-79.437067,N,N,0,N,N,5106,51037,51003,2024-2025
3954,243744,Stanford University,M,Stanford,CA,94305,06,06085,Santa Clara County,21,...,-122.167359,41940,"San Jose-Sunnyvale-Santa Clara, CA",1,488,"San Jose-San Francisco-Oakland, CA",0616,06023,06013,2024-2025
4690,440916,Southern University Law Center,M,Baton Rouge,LA,70813,22,22033,East Baton Rouge Parish,12,...,-91.194417,12940,"Baton Rouge, LA",1,132,"Baton Rouge-Hammond, LA",2206,22063,22014,2024-2025
6305,494737,Yeshiva Yesoda Hatorah Vetz Chaim,M,Brooklyn,NY,11211-7106,36,36047,Kings County,11,...,-73.961026,35620,"New York-Newark-Jersey City, NY-NJ",1,408,"New York-Newark, NY-NJ-CT-PA",3607,36050,36018,2024-2025

In [84]:
postsecondary["CBSA"].value_counts()

CBSA
35620    377
N        297
31080    264
16980    182
33100    153
        ...
47620      1
46020      1
38500      1
14100      1
24740      1
Name: count, Length: 787, dtype: int64

In [85]:
postsecondary["NMCBSA"].value_counts()

NMCBSA
New York-Newark-Jersey City, NY-NJ           377
N                                            297
Los Angeles-Long Beach-Anaheim, CA           264
Chicago-Naperville-Elgin, IL-IN              182
Miami-Fort Lauderdale-West Palm Beach, FL    153
                                            ...
Warren, PA                                     1
Truckee-Grass Valley, CA                       1
Plymouth, IN                                   1
Bloomsburg-Berwick, PA                         1
Greenville, MS                                 1
Name: count, Length: 787, dtype: int64

As we can see from the analysis above, we are missing values in some columns, specifically in the `CBSA`, the `NMCBSA`, and the `STREET` columns. The notation "N" & "M" likely indicates the missing data.

The "N" likely means that the public school in question is probably not in a CBSA. We verify this using an example below:

In [87]:
test = postsecondary[postsecondary["CBSA"] == "N"]
test.head()

,UNITID,NAME,STREET,CITY,STATE,ZIP,STFIP,CNTY,NMCNTY,LOCALE,...,LON,CBSA,NMCBSA,CBSATYPE,CSA,NMCSA,CD,SLDL,SLDU,SCHOOLYEAR
31,101587,University of West Alabama,Station One,Livingston,AL,35470,01,01119,Sumter County,43,...,-88.186329,N,N,0,N,N,0107,01071,01024,2024-2025
32,101602,Lurleen B Wallace Community College,1000 Dannelly Blvd.,Andalusia,AL,36420-1224,01,01039,Covington County,41,...,-86.452262,N,N,0,N,N,0101,01092,01031,2024-2025
33,101648,Marion Military Institute,1101 Washington St,Marion,AL,36756-3207,01,01105,Perry County,43,...,-87.322041,N,N,0,N,N,0107,01067,01023,2024-2025
41,101994,Reid State Technical College,100 and Hwy 83,Evergreen,AL,36401,01,01035,Conecuh County,43,...,-86.964797,N,N,0,N,N,0102,01068,01023,2024-2025
66,102711,Alaska Vocational Technical Center,PO Box 889,Seward,AK,99664-0889,02,02122,Kenai Peninsula Borough,43,...,-149.444487,N,N,0,N,N,0200,02005,0200C,2024-2025

Andalusia, AL, is located in Covington County. Covington County is not in a CBSA (according to [this map](https://www2.census.gov/geo/maps/metroarea/stcbsa_pg/Feb2013/cbsa2013_AL.pdf) of CBSAs in Alabama).

Similarly, Livingston, AL, is located in Sumter County. Sumter County is not in a CBSA according to the same map.

As a result, the missing values in the `CBSA` columns are highly likely due to the fact that these public schools are located in a region that is not encompassed by a CBSA. As a result, this missing data is likely intentional and not retrievable.

Ideally we should be more thorough and check every single entry, but doing so would require much more data (for example, every single city/county in every state) and is likely not feasible given the timeline of the project. This will be considered for future work.

This missing data in the `STREET` column is likely recoverable with a quick Google search on each of these institutions. There are only about 20 entries with this issue, so if we wanted to do this it is very much possible.

#### Accuracy

In [88]:
postsecondary["CITY"].value_counts()

CITY
New York            76
Chicago             72
Houston             67
Los Angeles         56
Brooklyn            53
                    ..
SOUTHFILED USA       1
East Point           1
Suprise              1
Maryland Heights     1
Lithia Springs       1
Name: count, Length: 2376, dtype: int64

In [90]:
postsecondary["STREET"].value_counts()

STREET
M                            11
One College Drive             6
100 College Drive             4
One University Place          4
One University Avenue         3
                             ..
4454 Breton Road SE           1
725 Howard Avenue             1
55 Canada del Rancho          1
4842 Cypress Garden Road      1
560 Thornton Rd Suite 119     1
Name: count, Length: 6505, dtype: int64

This dataset suffers from both syntactic and semantic errors.

We can see that there is inconsistent capitalization in the `CITY` names. One entry in particular is all upper-case, while the other ones are title-cased.

The one upper-case entry is also named "SOUTHFILED USA," which is very likely not the name of a city. Even if we removed the "USA" part, "SOUTHFILED" is also probably not the name of a city (even if "Southfield" would be).

We can likely fix the syntactic errors, but the semantic errors will require a bit more care to fix. We would need to verify and consult multiple sources to verify the facts for those semantic errors.

#### Consistency

A rule that must be satisfied is that each CBSA code should match to exactly 1 NMCBSA. We check that below.

In [91]:
cbsa_counts = postsecondary["CBSA"].value_counts()
nmcbsa_counts = postsecondary["NMCBSA"].value_counts()

for ((k1, _), (k2, _)) in zip(cbsa_counts.items(), nmcbsa_counts.items()):
    if k1 != "N":
        count_cbsa = cbsa_counts[k1]
        count_nmcbsa = nmcbsa_counts[k2]
        assert(count_cbsa == count_nmcbsa)
    else:
        assert(cbsa_counts[k1] == nmcbsa_counts[k2])

print("Assertions Passed")

Assertions Passed

The counts for each CBSA and NMCBSA match. While we can also check the other columns (namely `CSA` and `NMCSA`), we will remove those columns when we process the data in the data cleaning stage.

#### Timeliness

This particular dataset will not change over time. We are using the 2024-25 school location data from the Education Department, which should not change after the data is published. The data we see now should be the same into the future.

This data is from the 2024-25 school year, the most recent data available as of April 2026. This data should be suitable to use until the 2025-26 school year data is published by the Education Department.